name: flutter_mapp_clean_architecture
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  dio: ^5.3.2
  dartz: ^0.10.1
  data_connection_checker_tv: ^0.3.5-nullsafety
  provider: ^6.0.5
  path_provider: ^2.1.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.4
  logger: ^2.0.2+1
  intl: ^0.19.0
  flutter_native_splash: ^2.3.11
  smooth_page_indicator: ^1.1.0
  lottie: ^3.0.0
  iconsax: ^0.0.8
  badges: ^3.1.2
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/email_images/
    - assets/images/onboarding_images/
    - assets/images/banners/
    - assets/images/products/
    - assets/logos/
    - assets/logos/brands/
    - assets/icons/
    - assets/icons/categories/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic