// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBgyEke3Cg-V2yA3lrXsIKzsf5CRhvhks',
    appId: '1:675042181457:web:5cf828733c65d99d641370',
    messagingSenderId: '675042181457',
    projectId: 'fluttercleanarchitecture-78857',
    authDomain: 'fluttercleanarchitecture-78857.firebaseapp.com',
    storageBucket: 'fluttercleanarchitecture-78857.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7wjTwzQSfZFYGrIsozxVL1qZ4_H_uU-Y',
    appId: '1:675042181457:android:9b10b5f5acaf53ec641370',
    messagingSenderId: '675042181457',
    projectId: 'fluttercleanarchitecture-78857',
    storageBucket: 'fluttercleanarchitecture-78857.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4uxodEifScFLpCK-GgoFCvAX188Esd4w',
    appId: '1:675042181457:ios:55cf5d4af6835197641370',
    messagingSenderId: '675042181457',
    projectId: 'fluttercleanarchitecture-78857',
    storageBucket: 'fluttercleanarchitecture-78857.appspot.com',
    iosBundleId: 'com.example.flutterMappCleanArchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4uxodEifScFLpCK-GgoFCvAX188Esd4w',
    appId: '1:675042181457:ios:55cf5d4af6835197641370',
    messagingSenderId: '675042181457',
    projectId: 'fluttercleanarchitecture-78857',
    storageBucket: 'fluttercleanarchitecture-78857.appspot.com',
    iosBundleId: 'com.example.flutterMappCleanArchitecture',
  );
}
